In [2]:
import numpy as np
import pandas as pd
from numpy.random import randn
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
print(df)

          W         X         Y         Z
A  0.049567 -0.557366  0.901852  0.816031
B  0.034007  0.086151  0.165431 -2.059171
C -1.145467  1.359683 -1.527514  0.671898
D -0.634317  1.217193  0.808619  1.566379
E -1.195694 -0.022732  1.817912 -0.555923


In [3]:
df['W']

A    0.049567
B    0.034007
C   -1.145467
D   -0.634317
E   -1.195694
Name: W, dtype: float64

In [13]:
import numpy as np
import pandas as pd
from numpy.random import randint
#np.random.seed(101)
df=pd.DataFrame(randint(0,21),['A','B','C','D','E'],['W','X','Y','Z'])
print(df)

   W  X  Y  Z
A  7  7  7  7
B  7  7  7  7
C  7  7  7  7
D  7  7  7  7
E  7  7  7  7


In [11]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
print(df)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [12]:
df[['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [15]:
df['NEW']=df['W']+df['Y']
print(df)

   W  X  Y  Z  NEW
A  7  7  7  7   14
B  7  7  7  7   14
C  7  7  7  7   14
D  7  7  7  7   14
E  7  7  7  7   14


In [19]:
import numpy as np
import pandas as pd
from numpy.random import randint
df=pd.DataFrame(randint(80,100,15).reshape(5,3),index='A B C D E'.split(),columns='Phy Chem Maths'.split())
print(df)

   Phy  Chem  Maths
A   91    97     86
B   91    95     89
C   93    88     84
D   88    80     94
E   85    92     88


In [24]:
df['Total']=df['Phy']+df['Chem']+df['Maths']
df['Percentage']=(df['Total']/300)*100
df

Phy  Chem  Maths  Total  Percentage
A   91    97     86    274   91.333333
B   91    95     89    275   91.666667
C   93    88     84    265   88.333333
D   88    80     94    262   87.333333
E   85    92     88    265   88.333333

In [34]:
#df.loc['C']
df.iloc[2]

Phy            93.000000
Chem           88.000000
Maths          84.000000
Total         265.000000
Percentage     88.333333
Name: C, dtype: float64

In [41]:
booldf=df>90
booldf

Phy   Chem  Maths  Total  Percentage
A   True   True  False   True        True
B   True   True  False   True        True
C   True  False  False   True       False
D  False  False   True   True       False
E  False   True  False   True       False

In [42]:
df[booldf]

Phy  Chem  Maths  Total  Percentage
A  91.0  97.0    NaN    274   91.333333
B  91.0  95.0    NaN    275   91.666667
C  93.0   NaN    NaN    265         NaN
D   NaN   NaN   94.0    262         NaN
E   NaN  92.0    NaN    265         NaN

In [43]:
df

Phy  Chem  Maths  Total  Percentage
A   91    97     86    274   91.333333
B   91    95     89    275   91.666667
C   93    88     84    265   88.333333
D   88    80     94    262   87.333333
E   85    92     88    265   88.333333

In [44]:
df.reset_index()

index  Phy  Chem  Maths  Total  Percentage
0     A   91    97     86    274   91.333333
1     B   91    95     89    275   91.666667
2     C   93    88     84    265   88.333333
3     D   88    80     94    262   87.333333
4     E   85    92     88    265   88.333333

In [45]:
newind='INDIA AUSTRALIA SRILANKA NEWZELAND HOLAND'.split()

In [46]:
df['States']=newind
df

Phy  Chem  Maths  Total  Percentage     States
A   91    97     86    274   91.333333      INDIA
B   91    95     89    275   91.666667  AUSTRALIA
C   93    88     84    265   88.333333   SRILANKA
D   88    80     94    262   87.333333  NEWZELAND
E   85    92     88    265   88.333333     HOLAND

In [54]:
df.drop('Maths',axis=1,inplace=True)
#hide a coloumn

In [55]:
df['Total']=sum(df)

Phy  Chem  Total  Percentage
A   91    97    274   91.333333
B   91    95    275   91.666667
C   93    88    265   88.333333
D   88    80    262   87.333333
E   85    92    265   88.333333

In [53]:
#delete a coloumn
del df['States']


KeyError: 'States'

In [58]:
df.set_index('Percentage',inplace=True)
df

Phy  Chem
Percentage           
91.333333    91    97
91.666667    91    95
88.333333    93    88
87.333333    88    80
88.333333    85    92

In [59]:
df[(df['Phy']>80)&(df['Chem']>90)]

Phy  Chem
Percentage           
91.333333    91    97
91.666667    91    95
88.333333    85    92

In [60]:
df[(df['Phy']>80)|(df['Chem']>90)]

Phy  Chem
Percentage           
91.333333    91    97
91.666667    91    95
88.333333    93    88
87.333333    88    80
88.333333    85    92

In [61]:
df.count

<bound method DataFrame.count of             Phy  Chem
Percentage           
91.333333    91    97
91.666667    91    95
88.333333    93    88
87.333333    88    80
88.333333    85    92>

In [62]:
outside=['61','62','61','62','62']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)
print(outside)
print(hier_index)
list(zip(outside,inside))

['61', '62', '61', '62', '62']
MultiIndex(levels=[['61', '62'], [1, 2, 3]],
           labels=[[0, 1, 0, 1, 1], [0, 1, 2, 0, 1]])


[('61', 1), ('62', 2), ('61', 3), ('62', 1), ('62', 2)]

In [66]:
import numpy as np
import pandas as pd
df1=pd.DataFrame(np.random.rand(5,2),index=hier_index,columns=['A','B'])
df1

A         B
61 1  0.701371  0.487635
62 2  0.680678  0.521548
61 3  0.043397  0.223937
62 1  0.575205  0.120434
   2  0.500117  0.138010

In [68]:
df1.loc['61']

A         B
1  0.701371  0.487635
3  0.043397  0.223937

In [70]:
df1.index.names=['Group','Num']

In [71]:
df1

A         B
Group Num                    
61    1    0.701371  0.487635
62    2    0.680678  0.521548
61    3    0.043397  0.223937
62    1    0.575205  0.120434
      2    0.500117  0.138010

In [77]:
import pandas as pd
data={'Company':['Google','WhatsApp','Facebook','WhatsApp'],
      'Person':['Sam','Charlie','Anubhav','Paul'],
      'Sales':[200,300,400,500]}
df2=pd.DataFrame(data)
df2

Company   Person  Sales
0    Google      Sam    200
1  WhatsApp  Charlie    300
2  Facebook  Anubhav    400
3  WhatsApp     Paul    500

In [78]:
df2.groupby('Company').mean()

Sales
Company        
Facebook    400
Google      200
WhatsApp    400

In [80]:
df2.max()

Company    WhatsApp
Person          Sam
Sales           500
dtype: object

In [81]:
df2.describe()

Sales
count    4.000000
mean   350.000000
std    129.099445
min    200.000000
25%    275.000000
50%    350.000000
75%    425.000000
max    500.000000

In [82]:
df2.count()

Company    4
Person     4
Sales      4
dtype: int64

In [83]:
df2.std()

Sales    129.099445
dtype: float64

In [86]:
df2.describe().transpose()

count   mean         std    min    25%    50%    75%    max
Sales    4.0  350.0  129.099445  200.0  275.0  350.0  425.0  500.0

In [91]:
import numpy as np
from scipy import linalg
A= np.array([[1,2,3],[4,5,6],[7,8,8]])
linalg.det(A)

2.999999999999997

In [92]:
P,L,U=linalg.lu(A)

In [93]:
P

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]])

In [94]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.14285714,  1.        ,  0.        ],
       [ 0.57142857,  0.5       ,  1.        ]])

In [95]:
U

array([[ 7.        ,  8.        ,  8.        ],
       [ 0.        ,  0.85714286,  1.85714286],
       [ 0.        ,  0.        ,  0.5       ]])

In [96]:
np.dot(L,U)

array([[ 7.,  8.,  8.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [98]:
EW,EV=linalg.eig(A)

In [99]:
EW

array([ 15.55528261+0.j,  -1.41940876+0.j,  -0.13587385+0.j])

In [100]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])