In [1]:
import numpy as np
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [3]:
a=np.array([0,1,2,3])
print (a)

[0 1 2 3]


In [5]:
l=range(1000)
%timeit [i**2 for i in l]

10000 loops, best of 3: 93.3 µs per loop


In [7]:
a=np.arange(1000)
%timeit a**2

The slowest run took 26.74 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.72 µs per loop


In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(1,100,30)

array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

In [16]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.49078324, 0.53565302, 0.42507273, 0.86319626, 0.58106905])

In [18]:
np.random.rand(4,4)

array([[0.0407928 , 0.32104318, 0.82765844, 0.60726881],
       [0.88920617, 0.73370275, 0.47827561, 0.80155119],
       [0.6739771 , 0.62295506, 0.3556655 , 0.48253485],
       [0.34298513, 0.99379289, 0.30982303, 0.02477194]])

In [20]:
np.random.randn(4,4)

array([[-0.06568196,  0.87206764, -0.22467118,  0.26254634],
       [ 0.40735775, -0.62083503,  0.63030857,  0.69306008],
       [ 0.35087408, -1.58495366,  0.52849023, -0.7450685 ],
       [-0.34093206,  0.48508878,  1.04419829, -0.07688685]])

In [23]:
np.random.randint(1,100)

56

In [25]:
randarr=np.random.randint(0,50,10)
randarr

array([13, 40, 34, 26, 35, 25, 44, 48,  5, 26])

In [33]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
randarr.max()

48

In [36]:
randarr.argmax()

7

In [37]:
arr.ndim

1

In [38]:
from numpy.random import randint
randint(2,10)

7

In [39]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[8]

8

In [41]:
arr[1:5]

array([1, 2, 3, 4])

In [42]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [43]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,  99,   6,   7,   8,   9,  10])

In [52]:
slice_of_arr=arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,  99])

In [50]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [53]:
arr_copy=arr.copy()
arr

array([100, 100, 100, 100, 100,  99,   6,   7,   8,   9,  10])

In [54]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr=np.arange(0,11)
arr

In [ ]:
i=input("Enter a number")
arr=input(np.random.rand(i))
arr

In [ ]:
random.ra

array([99, 99, 99, 99, 99, 99])

ValueError: cannot reshape array of size 25 into shape (2,2)