In [1]:
import numpy as np
import pandas as pd
from numpy.random import randn
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
print(df)

          W         X         Y         Z
A  1.157088  0.279659 -0.957324  0.281448
B  0.980354  1.859123  0.734827 -0.813337
C -0.975540 -0.296648 -1.074749 -0.747968
D  0.686814  0.904111  0.479993 -1.892486
E -0.889619 -0.546528  0.883241  0.766969


In [2]:
df['W']

A    1.157088
B    0.980354
C   -0.975540
D    0.686814
E   -0.889619
Name: W, dtype: float64

In [9]:
import numpy as np
import pandas as pd
from numpy.random import randint
df=pd.DataFrame(randint(0,21),['A','B','C','D','E'],['W','X','Y','Z'])
print(df)

   W  X  Y  Z
A  5  5  5  5
B  5  5  5  5
C  5  5  5  5
D  5  5  5  5
E  5  5  5  5


In [16]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
print(df)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [17]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [19]:
df['new']=df['W']+df['Z']
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [23]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)
df=pd.DataFrame(randn(5,3),['A','B','C','D','E'],['PHY','CHEM','MATH'])
print(df)

        PHY      CHEM      MATH
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001
E  0.188695 -0.758872 -0.933237


In [21]:
df['Total']=df['PHY']+df['CHEM']+df['MATH']
df

PHY      CHEM      MATH     Total
A  2.706850  0.628133  0.907969  4.242952
B  0.503826  0.651118 -0.319318  0.835626
C -0.848077  0.605965 -2.018168 -2.260280
D  0.740122  0.528813 -0.589001  0.679935
E  0.188695 -0.758872 -0.933237 -1.503414

In [24]:
df['Total']=df['PHY']+df['CHEM']+df['MATH']
df

PHY      CHEM      MATH     Total
A  2.706850  0.628133  0.907969  4.242952
B  0.503826  0.651118 -0.319318  0.835626
C -0.848077  0.605965 -2.018168 -2.260280
D  0.740122  0.528813 -0.589001  0.679935
E  0.188695 -0.758872 -0.933237 -1.503414

In [27]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)
df=pd.DataFrame(randint(80,100,18).reshape(6,3),['A','B','C','D','E','F'],['PHY','CHEM','MATH'])
print(df)

   PHY  CHEM  MATH
A   91    97    86
B   91    95    89
C   93    88    84
D   88    80    94
E   85    92    88
F   97    99    95


In [29]:
df['Total']=df['PHY']+df['CHEM']+df['MATH']
df['Percent']=(df['Total']/300)*100
df

PHY  CHEM  MATH  Total    Percent
A   91    97    86    274  91.333333
B   91    95    89    275  91.666667
C   93    88    84    265  88.333333
D   88    80    94    262  87.333333
E   85    92    88    265  88.333333
F   97    99    95    291  97.000000

In [30]:
df['PHY']

A    91
B    91
C    93
D    88
E    85
F    97
Name: PHY, dtype: int64

In [34]:
df.iloc[3]

PHY         88.000000
CHEM        80.000000
MATH        94.000000
Total      262.000000
Percent     87.333333
Name: D, dtype: float64

In [41]:
df.loc['A']

PHY         91.000000
CHEM        97.000000
MATH        86.000000
Total      274.000000
Percent     91.333333
Name: A, dtype: float64

In [42]:
df['PHY']

A    91
B    91
C    93
D    88
E    85
F    97
Name: PHY, dtype: int64

In [43]:
df['PHY']>90

A     True
B     True
C     True
D    False
E    False
F     True
Name: PHY, dtype: bool

In [63]:
arr=(df['PHY']>90)
arr.count()


6

In [64]:
booldf=df>90
booldf

PHY   CHEM   MATH  Total  Percent
A   True   True  False   True     True
B   True   True  False   True     True
C   True  False  False   True    False
D  False  False   True   True    False
E  False   True  False   True    False
F   True   True   True   True     True

In [65]:
df[booldf]

PHY  CHEM  MATH  Total    Percent
A  91.0  97.0   NaN    274  91.333333
B  91.0  95.0   NaN    275  91.666667
C  93.0   NaN   NaN    265        NaN
D   NaN   NaN  94.0    262        NaN
E   NaN  92.0   NaN    265        NaN
F  97.0  99.0  95.0    291  97.000000

In [66]:
df

PHY  CHEM  MATH  Total    Percent
A   91    97    86    274  91.333333
B   91    95    89    275  91.666667
C   93    88    84    265  88.333333
D   88    80    94    262  87.333333
E   85    92    88    265  88.333333
F   97    99    95    291  97.000000

In [68]:
df.reset_index()

index  PHY  CHEM  MATH  Total    Percent
0     A   91    97    86    274  91.333333
1     B   91    95    89    275  91.666667
2     C   93    88    84    265  88.333333
3     D   88    80    94    262  87.333333
4     E   85    92    88    265  88.333333
5     F   97    99    95    291  97.000000

In [69]:
newind='INDIA AUTRALIA SRILANKA NEWZELAND HOLLAND'.split()

In [71]:
newind

['INDIA', 'AUTRALIA', 'SRILANKA', 'NEWZELAND', 'HOLLAND']

In [72]:
df

PHY  CHEM  MATH  Total    Percent
A   91    97    86    274  91.333333
B   91    95    89    275  91.666667
C   93    88    84    265  88.333333
D   88    80    94    262  87.333333
E   85    92    88    265  88.333333
F   97    99    95    291  97.000000

In [73]:
df.drop('Total',axis=1)
#hide the coloumn

PHY  CHEM  MATH    Percent
A   91    97    86  91.333333
B   91    95    89  91.666667
C   93    88    84  88.333333
D   88    80    94  87.333333
E   85    92    88  88.333333
F   97    99    95  97.000000

In [74]:
df

PHY  CHEM  MATH  Total    Percent
A   91    97    86    274  91.333333
B   91    95    89    275  91.666667
C   93    88    84    265  88.333333
D   88    80    94    262  87.333333
E   85    92    88    265  88.333333
F   97    99    95    291  97.000000

In [75]:
del df['Percent']

In [76]:
df

PHY  CHEM  MATH  Total
A   91    97    86    274
B   91    95    89    275
C   93    88    84    265
D   88    80    94    262
E   85    92    88    265
F   97    99    95    291

In [82]:
df.set_index('MATH',inplace=True)
df

PHY  CHEM
MATH           
86     91    97
89     91    95
84     93    88
94     88    80
88     85    92
95     97    99

In [83]:
df.count

<bound method DataFrame.count of       PHY  CHEM
MATH           
86     91    97
89     91    95
84     93    88
94     88    80
88     85    92
95     97    99>

In [ ]:
outside=['61','62','61','62','62','62']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_

In [84]:
import pandas as pd

data={'company':['Google','Whatsapp','Facebook','Whatsapp'],
         'Person':['Sam','Charlie','Anubhav','Paul'],
     'Sales':[200,300,400,500]}
df2=pd.DataFrame(data)
df2

Person  Sales   company
0      Sam    200    Google
1  Charlie    300  Whatsapp
2  Anubhav    400  Facebook
3     Paul    500  Whatsapp

In [86]:
df2.groupby('company').mean()

Sales
company        
Facebook    400
Google      200
Whatsapp    400

In [88]:
df2.max()

Person          Sam
Sales           500
company    Whatsapp
dtype: object

In [89]:
df2.count()

Person     4
Sales      4
company    4
dtype: int64

In [90]:
df2.std()

Sales    129.099445
dtype: float64

In [91]:
df2.describe()

Sales
count    4.000000
mean   350.000000
std    129.099445
min    200.000000
25%    275.000000
50%    350.000000
75%    425.000000
max    500.000000

In [93]:
df2.describe().transpose()

count   mean         std    min    25%    50%    75%    max
Sales    4.0  350.0  129.099445  200.0  275.0  350.0  425.0  500.0

In [96]:
import numpy as np
from scipy import linalg
A= np.array([[1,2,3],[4,5,6],[7,8,8]])
linalg.det(A)




#To find the deteerminant of a matrix

2.999999999999997

In [97]:
P,L,I=linalg.lu(A)
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [100]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [99]:
I

array([[7.        , 8.        , 8.        ],
       [0.        , 0.85714286, 1.85714286],
       [0.        , 0.        , 0.5       ]])

In [101]:
EW,EV=linalg.eig(A)
EW

array([15.55528261+0.j, -1.41940876+0.j, -0.13587385+0.j])

In [102]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])