In [1]:
arr=np.arange(0,11)
arr

NameError: name 'np' is not defined

In [2]:
import numpy as np
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [3]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.random.randint(6)

1

In [5]:
np.random.rand(1,100)

array([[0.11659524, 0.15405982, 0.98260853, 0.91741087, 0.6401971 ,
        0.18847984, 0.2584946 , 0.78009362, 0.84340286, 0.62922598,
        0.08356051, 0.53424424, 0.69060757, 0.90690498, 0.6014019 ,
        0.26527134, 0.38407417, 0.52443947, 0.389173  , 0.23851388,
        0.1102715 , 0.71859714, 0.87187254, 0.77179329, 0.37209503,
        0.56986811, 0.97570826, 0.67159274, 0.48131699, 0.79222022,
        0.65379003, 0.09135582, 0.95858554, 0.58957911, 0.61318652,
        0.80030165, 0.69261231, 0.26071903, 0.76284492, 0.04086862,
        0.52131397, 0.9092586 , 0.12022797, 0.3237576 , 0.78055446,
        0.17071318, 0.52210437, 0.995315  , 0.53467255, 0.91110411,
        0.93703894, 0.01865283, 0.65550521, 0.75815824, 0.61746514,
        0.13050515, 0.35164296, 0.45719495, 0.61428064, 0.17683378,
        0.60162065, 0.00609189, 0.25622474, 0.70829858, 0.13536441,
        0.77136503, 0.31947496, 0.21002629, 0.84282548, 0.43494663,
        0.52933703, 0.286529  , 0.68393851, 0.94

In [6]:
np.random.rand(10)

array([0.07672245, 0.29478   , 0.87264559, 0.39287474, 0.33730675,
       0.49456143, 0.43866301, 0.93178368, 0.60835784, 0.2553221 ])

In [7]:
n=input("Enter here")
arr=np.random.rand(n)
arr

Enter here6


array([0.35464573, 0.47433155, 0.9944915 , 0.68923654, 0.66844015,
       0.046755  ])

In [14]:
n=input("Enter here")
arr=np.random.rand(n)
print (arr)
for x in range(n):
    arr[x]=arr[x:x+1]*arr[x:x+1]*arr[x:x+1]
arr

Enter here2
[0.75173883 0.85992294]


array([0.42481608, 0.63588502])

In [15]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
arr_2d[0,1]

10

In [17]:
arr_2d[1]

array([20, 25, 30])

In [18]:
arr_2d[1][2]

30

In [19]:
arr_2d[:2,:1]

array([[ 5],
       [20]])

In [29]:
arr_2d[:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
arr_2d[:2,:1]

array([[ 5],
       [20]])

In [37]:
arr_2d[:2,2:]

array([[15],
       [30]])

In [38]:
arr_2d[:2,1:2]

array([[10],
       [25]])

In [39]:
arr_2d[:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d[:1,:2]

array([[ 5, 10]])

In [41]:
arr_2d[2:,:2]

array([[35, 40]])

In [42]:
arr_2d[1:,:1]

array([[20],
       [35]])

In [43]:
arr_2d[:1,1:]

array([[10, 15]])

In [44]:
arr_2d[1:,:1]

array([[20],
       [35]])

In [45]:
arr=np.arange(1,11)

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [49]:
bool_arr=arr>5

In [50]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [51]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [52]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [53]:
arr[arr<3]

array([1, 2])

In [54]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [57]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])